[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "d3159038a1b06a55f98d733f5a864bf655c7f246"
owners = ["Glyceri"]
	changelog = """
    [2.3.0.10]
    Now shows version number on windows.
    Uses BNpcName name instead of Pet name fixing some display names not renaming properly.
"""
